language: python
python: 3.5
env:
  matrix:
   - TOXENV=py26
   - TOXENV=py27
   - TOXENV=py32
   - TOXENV=py33
   - TOXENV=py34
   - TOXENV=py35
   - TOXENV=py36
   - TOXENV=pypy
   - TOXENV=flake8
before_install:
  - git submodule update --init
  - python setup.py dataset
install:
  - pip install tox
  - if test "$TOXENV" = py36 ; then pip install coveralls ; fi
  - if test "$TOXENV" = py32 ; then pip install "virtualenv<14.0.0" ; fi
script: tox
after_script:
  - if test "$TOXENV" = py36 ; then coveralls ; fi
