language: python
matrix:
  include:
    # Drop Support py26
    # - python: 2.6
    #   env: TOXENV=py26
    - python: 2.7
      env: TOXENV=py27
    # Drop Support py32
    # - python: 3.4
    #   env: TOXENV=py32
    - python: 3.4
      env: TOXENV=py33
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
    - python: pypy
      env: TOXENV=pypy
    - python: 3.7
      env: TOXENV=flake8
before_install:
  - git submodule update --init
install:
  - pip install tox
  - if test "$TOXENV" = py37 ; then pip install coveralls ; fi
  # - if test "$TOXENV" = py32 ; then pip install --upgrade "virtualenv<14.0.0" "setuptools<30.0.0"; fi
  - python setup.py dataset
script: 
  - tox
after_script:
  - if test "$TOXENV" = py37 ; then coveralls ; fi
